use crate::generators::{self, set_feature_flag};
use anyhow::{bail, Result};
use std::fs;
use std::path::Path;

pub fn run(feature: &str, force: bool, codegen: bool) -> Result<()> {
    generators::ensure_project()?;
    generators::validate_feature(feature)?;

    let key = generators::toml_key(feature).unwrap();
    if generators::feature_installed(key)? && !force {
        bail!("`{feature}` is already installed — use `--force` to re-run it");
    }

    match feature {
        "tailwind" => add_tailwind()?,
        "router" => generators::add_cargo_dep("leptos_router", "\"0.6\"")?,
        "lucide" => add_lucide()?,
        "ui" => add_ui()?,
        "api" => add_api()?,
        "file-router" => crate::generators::pages_scan::install(codegen)?,
        _ => unreachable!(),
    }

    set_feature_flag(feature, true)?;
    println!("✔ added `{}`", feature);
    Ok(())
}

fn add_tailwind() -> Result<()> {
    if !Path::new("tailwind.config.js").exists() {
        fs::write(
            "tailwind.config.js",
            "/** @type {import('tailwindcss').Config} */\nmodule.exports = {\n  content: [\"./src/**/*.rs\", \"./index.html\"],\n  theme: { extend: {} },\n  plugins: [],\n};\n",
        )?;
    }
    fs::write(
        "style/main.css",
        "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n",
    )?;
    println!("  → style/main.css uses @tailwind directives");
    println!("  → build it with: npx tailwindcss -i style/main.css -o style/output.css --watch");
    Ok(())
}

fn add_lucide() -> Result<()> {
    generators::add_cargo_dep("leptos_icons", "\"0.3\"")?;
    fs::create_dir_all("src/components")?;
    generators::ensure_mod_line("src/components/mod.rs", "pub mod icons;")?;
    fs::write("src/components/icons.rs", ICONS_RS)?;
    Ok(())
}

fn add_ui() -> Result<()> {
    fs::create_dir_all("src/components/ui")?;
    generators::ensure_mod_line("src/components/mod.rs", "pub mod ui;")?;
    if !Path::new("src/components/ui/mod.rs").exists() {
        fs::write("src/components/ui/mod.rs", UI_MOD_RS)?;
    }
    Ok(())
}

fn add_api() -> Result<()> {
    generators::add_cargo_dep("reqwest", r#"{ version = "0.12", features = ["json"] }"#)?;
    generators::add_cargo_dep("serde", r#"{ version = "1", features = ["derive"] }"#)?;
    fs::create_dir_all("src/api")?;
    fs::write("src/api/mod.rs", API_MOD)?;
    generators::ensure_mod_line("src/lib.rs", "pub mod api;")?;
    Ok(())
}

const ICONS_RS: &str = r#"// Generated by `cargo leptosx add lucide`.
// Re-exports the `leptos_icons` icon data so the app can `use crate::components::icons::*;`.
pub use leptos_icons::*;

// Example — pull the icon data you want from `icondata`:
//   use icondata::{AiGithubOutlined, BiHomeSmileFill};
//   view! { <Icon icon=AiGithubOutlined width="24" height="24"/> }
"#;

const UI_MOD_RS: &str = r#"// Generated by `cargo leptosx add ui`.
// A small component library. Add your primitives here, e.g.:
//   pub mod button;
//   pub mod card;
use leptos::*;

#[component]
pub fn Button(children: Children) -> impl IntoView {
    view! {
        <button class="btn">{children()}</button>
    }
}
"#;

/// Template written to `src/api/mod.rs` by `cargo leptosx add api`.
const API_MOD: &str = r##"// Generated by `cargo leptosx add api`.
// Small typed fetch wrapper. Usage:
//   let api = Api::new("https://example.com");
//   let user: User = api.get("/users/1").await?;
use serde::de::DeserializeOwned;
use serde::Serialize;

#[derive(Clone)]
pub struct Api {
    pub base_url: String,
}

impl Api {
    pub fn new(base_url: impl Into<String>) -> Self {
        Self { base_url: base_url.into() }
    }

    pub async fn get<T: DeserializeOwned>(&self, path: &str) -> Result<T, String> {
        self.request("GET", path, None::<&()>).await
    }

    pub async fn post<T: DeserializeOwned, B: Serialize>(
        &self,
        path: &str,
        body: &B,
    ) -> Result<T, String> {
        self.request("POST", path, Some(body)).await
    }

    pub async fn put<T: DeserializeOwned, B: Serialize>(
        &self,
        path: &str,
        body: &B,
    ) -> Result<T, String> {
        self.request("PUT", path, Some(body)).await
    }

    pub async fn patch<T: DeserializeOwned, B: Serialize>(
        &self,
        path: &str,
        body: &B,
    ) -> Result<T, String> {
        self.request("PATCH", path, Some(body)).await
    }

    pub async fn delete<T: DeserializeOwned>(&self, path: &str) -> Result<T, String> {
        self.request("DELETE", path, None::<&()>).await
    }

    async fn request<T: DeserializeOwned, B: Serialize>(
        &self,
        method: &str,
        path: &str,
        body: Option<&B>,
    ) -> Result<T, String> {
        let url = format!("{}{}", self.base_url, path);
        let client = reqwest::Client::new();
        let mut req = client.request(
            reqwest::Method::from_bytes(method.as_bytes()).map_err(|e| e.to_string())?,
            url,
        );
        if let Some(body) = body {
            req = req.json(body);
        }
        req.send()
            .await
            .map_err(|e| e.to_string())?
            .error_for_status()
            .map_err(|e| e.to_string())?
            .json::<T>()
            .await
            .map_err(|e| e.to_string())
    }
}
"##;