//! File-based routing (Next.js style).
//!
//! Installs a `build.rs` that scans `src/pages/` and emits a `pub fn routes()`
//! containing a `<Routes>` block:
//!
//! ```text
//! src/pages/index.rs            -> "/"
//! src/pages/about.rs            -> "/about"
//! src/pages/blog/[slug].rs      -> "/blog/:slug"
//! src/pages/blog/+layout.rs     -> wraps every route under /blog
//! src/pages/settings/[...rest]  -> "/settings/*rest"
//! ```
//!
//! Every page file exports a `Page` component; every `+layout.rs` exports a
//! `Layout` component rendering an `<Outlet/>`. Duplicate routes panic the
//! build with a clear message.
//!
//! By default routes are emitted into `OUT_DIR` and `include!`-ed from
//! `src/app.rs`. With `--codegen` they are written to `src/routes.rs` (checked
//! in) and referenced as `crate::routes::routes()`. The mode is stored in
//! `leptosx.toml` as `[features] file_router_codegen`.

use anyhow::Result;
use std::fs;
use std::path::Path;
use toml_edit::value;

pub fn install(codegen: bool) -> Result<()> {
    install_in(Path::new("."), codegen)
}

/// Install file routing rooted at `root`. Used by `add file-router` and
/// automatically by `new` when the router is selected.
pub fn install_in(root: &Path, codegen: bool) -> Result<()> {
    let leptosx = root.join("leptosx.toml");
    let content = fs::read_to_string(&leptosx)?;
    let doc = content.parse::<toml_edit::Document>()?;
    let rendering = doc["project"]["rendering"].as_str().unwrap_or("csr").to_string();
    let app_name = doc["project"]["name"].as_str().unwrap_or("app").to_string();
    let crate_name = app_name.replace('-', "_");

    fs::write(root.join("build.rs"), BUILD_RS)?;

    let mut doc = content.parse::<toml_edit::Document>()?;
    doc["features"]["router"] = value(true);
    doc["features"]["file_router"] = value(true);
    doc["features"]["file_router_codegen"] = value(codegen);
    fs::write(&leptosx, doc.to_string())?;

    // The generated app.rs uses leptos_router, so make sure the dependency exists.
    let mut cargo = fs::read_to_string(root.join("Cargo.toml"))?.parse::<toml_edit::Document>()?;
    let has_router = cargo
        .get("dependencies")
        .and_then(|d| d.as_table_like())
        .map(|t| t.get("leptos_router").is_some())
        .unwrap_or(false);
    if !has_router {
        cargo["dependencies"]["leptos_router"] = value("0.6");
        fs::write(root.join("Cargo.toml"), cargo.to_string())?;
    }

    // routes.rs handles the module tree, so pages/mod.rs only declares nothing.
    fs::write(
        root.join("src/pages/mod.rs"),
        "// page modules are generated by build.rs\n",
    )?;

    let ssr = rendering == "ssr-hydration";
    let app_rs = if ssr {
        if codegen {
            SSR_APP_CODEGEN.replace("{crate_name}", &crate_name)
        } else {
            SSR_APP_INCLUDE.replace("{crate_name}", &crate_name)
        }
    } else if codegen {
        CSR_APP_CODEGEN.to_string()
    } else {
        CSR_APP_INCLUDE.to_string()
    };
    fs::write(root.join("src/app.rs"), app_rs)?;

    if codegen {
        let lib_rs = fs::read_to_string(root.join("src/lib.rs")).unwrap_or_default();
        if !lib_rs.contains("pub mod routes;") {
            fs::write(root.join("src/lib.rs"), format!("{}pub mod routes;\n", lib_rs))?;
        }
    }

    println!("  → wrote build.rs (scans src/pages/ each build)");
    if codegen {
        println!("  → writes src/routes.rs (checked in) and registers `pub mod routes;`");
    } else {
        println!("  → routes are generated into OUT_DIR and included by src/app.rs");
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// build.rs template. The same script serves both modes; it reads the codegen
// flag from leptosx.toml at build time.
// ---------------------------------------------------------------------------

const BUILD_RS: &str = r##"// Generated by `cargo leptosx add file-router`.
// Scans src/pages/ and emits a `pub fn routes()` <Routes> block at build time.
use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

struct Page {
    url: String,
    file: String,
}

struct Layout {
    dir: String,
    file: String,
}

fn main() {
    println!("cargo:rerun-if-changed=src/pages");
    let manifest = env::var("CARGO_MANIFEST_DIR").unwrap();
    let codegen = fs::read_to_string(Path::new(&manifest).join("leptosx.toml"))
        .unwrap_or_default()
        .contains("file_router_codegen = true");
    let pages_dir = Path::new("src/pages");
    let mut pages: Vec<Page> = Vec::new();
    let mut layouts: Vec<Layout> = Vec::new();
    if pages_dir.exists() {
        collect(pages_dir, pages_dir, "", &mut pages, &mut layouts);
    }

    let mut seen: HashMap<&str, &str> = HashMap::new();
    for p in &pages {
        if let Some(prev) = seen.insert(&p.url, &p.file) {
            panic!("duplicate route `{}` ({} and {})", p.url, prev, p.file);
        }
    }

    // routes.rs lives in src/ in codegen mode, in OUT_DIR otherwise.
    let prefix = if codegen {
        "pages/".to_string()
    } else {
        format!("{}/src/pages/", manifest.replace('\\', "/"))
    };

    let mut out = String::new();
    out.push_str("use leptos::*;\nuse leptos_router::*;\n\n");
    for (i, p) in pages.iter().enumerate() {
        out.push_str(&format!(
            "#[path = \"{}{}\"]\nmod __leptosx_page_{};\n",
            prefix, p.file, i
        ));
    }
    for (i, l) in layouts.iter().enumerate() {
        out.push_str(&format!(
            "#[path = \"{}{}\"]\nmod __leptosx_layout_{};\n",
            prefix, l.file, i
        ));
    }
    out.push_str(
        "\n#[component]\nfn NotFound() -> impl IntoView {\n    view! { <h1>\"404 — Not Found\"</h1> }\n}\n\n",
    );
    out.push_str("pub fn routes() -> impl IntoView {\n    view! {\n        <Routes>\n");

    let mut chains: Vec<Vec<usize>> = Vec::new();
    for p in &pages {
        let mut chain: Vec<usize> = layouts
            .iter()
            .enumerate()
            .filter(|(_, l)| l.dir.is_empty() || p.url == l.dir || p.url.starts_with(&format!("{}/", l.dir)))
            .map(|(idx, _)| idx)
            .collect();
        chain.sort_by_key(|&idx| layouts[idx].dir.len());
        chains.push(chain);
    }

    let mut groups: BTreeMap<usize, Vec<usize>> = BTreeMap::new();
    for (i, p) in pages.iter().enumerate() {
        if chains[i].is_empty() {
            out.push_str(&format!(
                "            <Route path=\"{}\" view=__leptosx_page_{}::Page/>\n",
                p.url, i
            ));
        } else {
            groups.entry(chains[i][0]).or_default().push(i);
        }
    }

    for (outer, page_idxs) in &groups {
        out.push_str(&format!(
            "            <Route path=\"{}\" view=__leptosx_layout_{}::Layout>\n",
            layouts[*outer].dir, outer
        ));
        for &i in page_idxs {
            let mut prev = layouts[*outer].dir.clone();
            for &lid in chains[i].iter().skip(1) {
                let rel = strip(&layouts[lid].dir, &prev);
                out.push_str(&format!(
                    "                <Route path=\"{}\" view=__leptosx_layout_{}::Layout>\n",
                    rel, lid
                ));
                prev = layouts[lid].dir.clone();
            }
            let rel = strip(&pages[i].url, &prev);
            out.push_str(&format!(
                "                    <Route path=\"{}\" view=__leptosx_page_{}::Page/>\n",
                rel, i
            ));
            for _ in chains[i].iter().skip(1) {
                out.push_str("                </Route>\n");
            }
        }
        out.push_str("            </Route>\n");
    }

    out.push_str("            <Route path=\"*path\" view=NotFound/>\n");
    out.push_str("        </Routes>\n    }\n}\n");

    if codegen {
        fs::write(Path::new(&manifest).join("src/routes.rs"), out).unwrap();
    } else {
        let out_dir = env::var("OUT_DIR").unwrap();
        fs::write(PathBuf::from(out_dir).join("routes.rs"), out).unwrap();
    }
}

fn strip(url: &str, prefix: &str) -> String {
    if prefix.is_empty() {
        url.trim_start_matches('/').to_string()
    } else if url == prefix {
        String::new()
    } else if let Some(rest) = url.strip_prefix(&format!("{}/", prefix)) {
        rest.to_string()
    } else {
        url.to_string()
    }
}

fn collect(root: &Path, dir: &Path, dir_url: &str, pages: &mut Vec<Page>, layouts: &mut Vec<Layout>) {
    let Ok(entries) = fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            let seg = path.file_name().unwrap().to_string_lossy().to_string();
            let seg_url = if let Some(param) = seg.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                format!(":{param}")
            } else {
                seg
            };
            let child_url = format!("/{}/{}", dir_url.trim_matches('/'), seg_url);
            let child_url = format!("/{}", child_url.trim_start_matches('/'));
            collect(root, &path, &child_url, pages, layouts);
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        if stem == "mod" {
            continue;
        }
        let rel = path.strip_prefix(root).unwrap();
        let file_rel = rel.to_string_lossy().replace('\\', "/");

        if stem.starts_with("+layout") {
            layouts.push(Layout { dir: dir_url.to_string(), file: file_rel });
            continue;
        }

        let mut segments: Vec<String> = dir_url
            .split('/')
            .filter(|s| !s.is_empty())
            .map(String::from)
            .collect();
        if stem != "index" {
            if let Some(param) = stem.strip_prefix("[...").and_then(|s| s.strip_suffix(']')) {
                segments.push(format!("*{param}"));
            } else if let Some(param) = stem.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
                segments.push(format!(":{param}"));
            } else {
                segments.push(stem);
            }
        }
        let url = if segments.is_empty() {
            "/".to_string()
        } else {
            format!("/{}", segments.join("/"))
        };
        pages.push(Page { url, file: file_rel });
    }
}
"##;

// ---------------------------------------------------------------------------
// app.rs rewrites for both modes
// ---------------------------------------------------------------------------

const CSR_APP_INCLUDE: &str = r#"use leptos::*;
use leptos_router::*;

include!(concat!(env!("OUT_DIR"), "/routes.rs"));

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            {routes()}
        </Router>
    }
}
"#;

const CSR_APP_CODEGEN: &str = r#"use leptos::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    view! {
        <Router>
            {crate::routes::routes()}
        </Router>
    }
}
"#;

const SSR_APP_INCLUDE: &str = r#"use crate::error_template::{AppError, ErrorTemplate};
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

include!(concat!(env!("OUT_DIR"), "/routes.rs"));

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/{crate_name}.css"/>
        <Title text="leptosx app"/>

        <Router fallback=|| {
            let mut outside_errors = Errors::default();
            outside_errors.insert_with_default_key(AppError::NotFound);
            view! {
                <ErrorTemplate outside_errors/>
            }
            .into_view()
        }>
            <main>
                {routes()}
            </main>
        </Router>
    }
}
"#;

const SSR_APP_CODEGEN: &str = r#"use crate::error_template::{AppError, ErrorTemplate};
use leptos::*;
use leptos_meta::*;
use leptos_router::*;

#[component]
pub fn App() -> impl IntoView {
    provide_meta_context();

    view! {
        <Stylesheet id="leptos" href="/pkg/{crate_name}.css"/>
        <Title text="leptosx app"/>

        <Router fallback=|| {
            let mut outside_errors = Errors::default();
            outside_errors.insert_with_default_key(AppError::NotFound);
            view! {
                <ErrorTemplate outside_errors/>
            }
            .into_view()
        }>
            <main>
                {crate::routes::routes()}
            </main>
        </Router>
    }
}
"#;